### ISSUE TITLE
Ability to switch on and off the pressure sensitivity of pen and pen-tablet

### ISSUE THREAD

**Issue by vohra64** [bk138/gromit-mpx#129] opened 2021-05-12 09:11 UTC
Gromit-mpx is an excellent software for screen annotations.

I have been using it with XP-Pen tablet and it picked up the input device nicely and is working well after a few changes in the config file.

While drawing on screen I noticed that it also picks up the pressure input from the pen and changes the thickness of the drawing. Typically, while writing with a pen, it makes the words to appear shabby. So there should be some button/function/ switch that could be activated to turn off and on the pressure sensitivity.

My request to add it in a future release. 

Meanwhile, if it can be done through some directive at compile time, it would be of help.

Thanks.

**Comment by bk138** [comment] 2021-05-12 09:58
Maybe a dupe of #92 ?

**Comment by vohra64** [comment] 2021-05-13 19:00
Thanks for your quick response. 

I just had at look at #92 and the solution to it in #115 ,
Yes part of my feature request is covered in it. I have two points here

1. The pressure sensitivity can be nullified as per #115 but it is not clear  whether it can be done through a directive or parameter in cfg file. If yes,  documentation need to be updated to indicate how,
2. My request is to add a switch to set the sensitivity on or off in the options item  of the menu that appears on right clicking the tray icon.

Thanks.

**Comment by vohra64** [comment] 2021-05-13 19:02
I accendently closed it so opened again.

**Comment by bk138** [comment] 2021-05-14 11:11
>     1. The pressure sensitivity can be nullified as per #115 but it is not clear  whether it can be done through a directive or parameter in cfg file. If yes,  documentation need to be updated to indicate how,

https://github.com/bk138/gromit-mpx/commit/2c7589da3f0e8108335295fca65859fe8c63a0e1 should answer this


>     2. My request is to add a switch to set the sensitivity on or off in the options item  of the menu that appears on right clicking the tray icon.

OK!

**Closed** 2021-05-14 11:18 UTC
Labels: feature-request, wontfix
