### ISSUE TITLE
Grabbing hotkey F9 from keyboard 3 failed.

### ISSUE THREAD

**Issue by Popolon** [bk138/gromit-mpx#98] opened 2020-09-27 13:52 UTC
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/gromit-mpx

**Describe the bug**

When gromit-mpx start, a window with the error message "Grabbing hotkey F9 from keyboard 3 failed. The drawing hotkey function will not work unless configured to use another key.", following by another one with F8 instead of F9, and following help. Both keys then doesn't work at the end.

 I tried to define several differents keys in the configuration file and in command line arguments, and the same messages with F9/F8 key appears the following help messages  display the key I choose, but those key don't work either. I tried HOTKEY = F1, "CTRL+F1", "CTRL+ALT+F1".

**To Reproduce**
launch XFCE 4.14 on Arch Linux session, start gromit-mpx (last git commit 1.3.1.xxx) in a terminal.

**Expected Behavior**

hotkey working.

**Desktop (please complete the following information):**
 - OS and version: Arch Linux
 - Xorg version used: Xorg-server 1.20.9 XFCE 4.14

**Additional context**

**Comment by bk138** [comment] 2020-09-27 14:07
Please check the info in #77.

**Comment by Popolon** [comment] 2020-09-27 20:12
Thank you, it seems that only the same hardware key works (z on an AZERTY == w on a QWERTY).

**Comment by bk138** [comment] 2020-09-27 20:34
You might want to file an issue with the XFCE guys as other desktops work fine in this regard. Maybe you can simply edit XFCE hotkeys? Anyway, closing as a dupe of #77 :-)

**Closed by bk138** 2020-09-27 20:34 UTC
Labels: answer-needed, bug, duplicate
