### ISSUE TITLE
Manjaro XFCE - ERROR: Grabbing hotkey from keyboard device 3 failed

### ISSUE THREAD

**Issue by artofit** [bk138/gromit-mpx#105] opened 2020-11-16 10:17 UTC
OS: Manjaro XFCE with latest updates, kernel 5.8
gromit-mpx: Pamac built from AUR.
keyboard: external via usb

**Describe the bug**
$ gromit-mpx -d
Could not open user config /home/toshpc/.config/gromit-mpx.cfg: Aucun fichier ou dossier de ce type
Could not open Flatpak config /app/etc/gromit-mpx/gromit-mpx.cfg: Aucun fichier ou dossier de ce type
Could not open system config /etc/gromit-mpx/gromit-mpx.cfg: Aucun fichier ou dossier de ce type
No usable config found, leaving tools unconfigured!
DEBUG: Ungrabbed all Devices.

(gromit-mpx:13969): libappindicator-CRITICAL **: 10:52:00.828: app_indicator_set_icon_full: assertion 'IS_APP_INDICATOR (self)' failed
DEBUG: Grabbing hotkeys 'F9' and 'F8' from keyboard '3' .
ERROR: Grabbing hotkey from keyboard device 3 failed.
ERROR: Grabbing undo key from keyboard device 3 failed.
Enabled Device 0: "Virtual core pointer", (Type: 0)
Now 1 enabled devices.
DEBUG: Ungrabbed all Devices.

(gromit-mpx:13969): libappindicator-CRITICAL **: 10:52:16.230: app_indicator_set_icon_full: assertion 'IS_APP_INDICATOR (self)' failed
DEBUG: Hiding window.
DEBUG: got configure event

(gromit-mpx:13969): Gdk-CRITICAL **: 10:52:16.609: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

-->

**Expected Behavior**

**Screenshots**

**Desktop (please complete the following information):**
System:    Host: toshpc Kernel: 5.8.18-1-MANJARO x86_64 bits: 64 Desktop: Xfce 4.14.2 Distro: Manjaro Linux 
Display: server: X.Org 1.20.9 driver: intel unloaded: modesetting resolution: 1920x1080~60Hz 

$ lsusb
Bus 003 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 005: ID 04f2:b307 Chicony Electronics Co., Ltd 
Bus 001 Device 004: ID 0471:083a Philips (or NXP) 
Bus 001 Device 003: ID 0bda:0138 Realtek Semiconductor Corp. RTS5138 Card Reader Controller
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
**Bus 002 Device 003: ID 03f0:064a HP, Inc HP USB Keyboard**
Bus 002 Device 002: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Additional context**
https://github.com/bk138/gromit-mpx/issues/77

**Comment by bk138** [comment] 2020-11-16 11:16
Hi!, What's the gromit-mpx version and did you try the workarounds in #77?

**Comment by bk138** [comment] 2020-11-16 11:17
All in all, isn't that a duplicate of #77?

**Comment by artofit** [comment] 2020-11-17 09:42
Hello
1. First I see that issue 77 is closed, so I did assume it was fixed.
2. Gromit: 1.3.31.r40.g4b77135-1
3. Maybe for you it's obvious how to change grabbing keys, so could you give an example to map for instance on CRTL+SHIFT and Windows key+SHIFT.
4. I'm not sure of what you refer as "the workarounds in #77?"


$ gromit-mpx --key "F7" --debug
Could not open user config /home/toshpc/.config/gromit-mpx.cfg: Aucun fichier ou dossier de ce type
Could not open Flatpak config /app/etc/gromit-mpx/gromit-mpx.cfg: Aucun fichier ou dossier de ce type
Could not open system config /etc/gromit-mpx/gromit-mpx.cfg: Aucun fichier ou dossier de ce type
No usable config found, leaving tools unconfigured!
DEBUG: Ungrabbed all Devices.

(gromit-mpx:4172): libappindicator-CRITICAL **: 10:34:43.052: app_indicator_set_icon_full: assertion 'IS_APP_INDICATOR (self)' failed
DEBUG: Grabbing hotkeys 'F7' and 'F8' from keyboard '3' .
ERROR: Grabbing hotkey from keyboard device 3 failed.
ERROR: Grabbing undo key from keyboard device 3 failed.
Enabled Device 0: "Virtual core pointer", (Type: 0)
Now 1 enabled devices.
DEBUG: Ungrabbed all Devices.

(gromit-mpx:4172): libappindicator-CRITICAL **: 10:34:45.134: app_indicator_set_icon_full: assertion 'IS_APP_INDICATOR (self)' failed
DEBUG: Hiding window.
DEBUG: got configure event

(gromit-mpx:4172): Gdk-CRITICAL **: 10:34:45.379: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

**Comment by bk138** [comment] 2020-11-17 10:12
> Hello
> 
>     1. First I see that issue 77 is closed, so I did assume it was fixed.

Closes issue either mean fixed or cannot-be-fixed. With XFCE it's the latter :-).


>     2. gromit-mpx: AUR 1.3.31.r40.g4b77135-1,
>        gromit-mpx>about displays version 1.4

Looks like current master, thanks!


>     3. Maybe for you it's obvious how to change grabbing keys, so could you give an example to map for instance on CRTL+SHIFT and Windows key+SHIFT.

https://github.com/bk138/gromit-mpx#how-to-use-it - btw you cannot map CTRL as it's a modifier to the hotkey, for Windows key I don't know. 

> 
>     4. I'm not sure of what you refer as "the workarounds in #77?"

The workaround is: define another hotkey that's not grabbed by XFCE, see https://github.com/bk138/gromit-mpx/issues/77#issuecomment-603962674.

**Comment by bk138** [comment] 2020-11-17 10:14
Long story short: I propose you try out ome other keys with the `--key` option. Maybe non-function keys. as other commenters in #77 suggest.

**Comment by bk138** [comment] 2020-11-17 10:15
@artofit Let's please continue in #77 to have info in one place.

**Closed by bk138** 2020-11-17 10:15 UTC
Labels: bug
