### ISSUE TITLE
Default config - Eraser Doesn't Work (?)

### ISSUE THREAD

**Issue by mikeperalta1** [bk138/gromit-mpx#119] opened 2021-02-04 21:59 UTC
**Describe the bug**
I'm not sure if this is indeed a bug for all systems, but it seems to be a config bug for mine. In the default configuration here: https://github.com/bk138/gromit-mpx/blob/f7a76980249ebd3fab98eabc48d5be0c6893f40b/data/gromit-mpx.cfg, the eraser is set only for Button3. But in my system, Button1 is always considered pressed when the pen is writing.

Therefore, this line doesn't work for erasing:
```
"default"[Button3] = "Eraser";
```

Instead, I had to change my config to the following:
```
"default"[Button1,Button3] = "Eraser";
```

**To Reproduce**
1. Install Gromit-MPX to Ubuntu 20.10
2. Initialize Wacom Pen buttons 1 and 3 to defaults, using xsetwacom
3. Start Gromit-MPX with default configuration
4. Draw a line with pen
5. Also with pen, use pen's "back button" (Button3) and try to erase

**Expected Behavior**
Erasing should work by default

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS and version: Ubuntu 20.10 (Groovy Gorilla)
 - Xorg version used: xorg/groovy,now 1:7.7+19ubuntu15 amd64
 - Wayland version used: xwayland/now 2:1.20.9-2ubuntu1.2~20.04.1 amd64
 

**Additional context**
Gromit-MPX: gromit-mpx/groovy,now 1.3.1-1 amd64

**Comment by bk138** [comment] 2021-02-05 09:52
That's a dupe of #16 which was fixed by 767f9a82b5fd9d1aa357c910b0f3a2fc4e6e692c which in turn appeared in release 1.4 so it seems you don't have that fix. I suggest you use the Flatpak to get the most recent version.

**Closed by bk138** 2021-02-05 09:52 UTC
Labels: bug, duplicate
