### ISSUE TITLE
Hot Keys not working in MX Linux

### ISSUE THREAD

**Issue by pannet1** [bk138/gromit-mpx#81] opened 2020-04-18 07:29 UTC
If i select toggle painting, i enter into painting mode but unable to toggle back to normal mode, because hot key are not working. 

1. Select Gromit-mpx from application menu
2. Complete the What is it and how to use it screens. Apply
3. Select toggle screen from status bar icon
4. toggle back with F9

**Desktop (please complete the following information):**
Gromix-mpx is already packaged in MX-Linux through debian repository

**Comment by bk138** [comment] 2020-04-18 08:16
Hi! Have you tried with another hotkey? See https://github.com/bk138/gromit-mpx#how-to-use-it how to change them.

**Comment by bk138** [comment] 2020-04-18 08:17
Please also check the info in #77. Might this issue be a duplicate?

**Comment by pannet1** [comment] 2020-04-18 15:07
Sorry, i saw the below issue after posting it. I am not able to add another function key too. However if i use other keys, 'w' for example, it works. i just ran
`gromit-mpx --key 'w'`

Can you please update the README.MD to show if hotkey modifier can be saved in config file.

> Hi! Have you tried with another hotkey? See https://github.com/bk138/gromit-mpx#how-to-use-it how to change them.

**Comment by bk138** [comment] 2020-04-18 15:38
Dupe of #77, let's track progress there.

**Closed by bk138** 2020-04-18 15:38 UTC
Labels: bug, duplicate
