### ISSUE TITLE
Window X is a temporary window without parent

### ISSUE THREAD

**Issue by measlytwerp** [bk138/gromit-mpx#65] opened 2019-03-06 05:52 UTC
When starting under GNOME 3.30.3 / Wayland I get the following output and none of the functionality works:

```Supported backends: x11 wayland 
Using backend: wayland
Enabled Device 0: "Core Pointer", (Type: 0)
Now 1 enabled devices.
Gdk-Message: 16:18:37.198: Window 0x55848fae1340 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 16:18:37.198: Window 0x55848fae1340 is a temporary window without parent, application will not be able to position it on screen.
```

Works fine under X11, however with the upcoming GNOME 3.32 fractional scaling doesn't work under X11 so I wanted to test everything ahead of release.

**Comment by bk138** [comment] 2019-03-06 08:12
Does it work when using X11?

**Comment by bk138** [comment] 2019-03-06 08:14
So it's actully two issues? If so. please open another one and provide as much context info as possible! :-)

**Comment by measlytwerp** [comment] 2019-03-06 10:24
Yeah, it's fine under X11, I accidentally malformed the code block above.

I'm running Arch Linux, up to date as of a few days ago, are there any specific packages I should check versions of? What else can I provide?

**Comment by bk138** [comment] 2019-03-06 11:35
Nice to know would be:

* GTK/GDK versions
* Gromit-MPX version ;-)
* X11 version
* Wayland version

**Comment by bk138** [comment] 2019-07-03 17:10
Tentatively closing, feel free to re-open in case the issue persists. Maybe it's a dupe of #27 anyway :-)

**Closed by bk138** 2019-07-03 17:10 UTC
Labels: answer-needed
