### ISSUE TITLE
Show again on Startup

### ISSUE THREAD

**Issue by guilhermesousa-cwi** [bk138/gromit-mpx#175] opened 2023-01-15 17:43 UTC
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/gromit-mpx

**Describe the bug**

In ubuntu.22.04.01 even disabling the option, it always appears when restarting the computer.

**To Reproduce**

**Expected Behavior**

By unchecking the checkbox, this information should no longer be displayed.

**Screenshots**

![image](https://user-images.githubusercontent.com/118919569/212557327-a89bb7d9-1460-4731-805b-6eb532aa594c.png)

**Environment (please complete the following information):**
 - Gromit-MPX version: 1.4.3
 - Flatpak
 - OS and version: OS: Ubuntu 22.04.1 LTS x86_64 | Kernel: 5.15.0-58-generic 
 - Desktop Environment and version: DE: GNOME 42.5 |
 - X11 or Wayland session: X11/XORG 
 
**Additional context**

nano ~/.config/autostart/gromit-mpx.desktop

![image](https://user-images.githubusercontent.com/118919569/212560805-eb79a2da-2ab4-4e04-92ec-06bf11e912fd.png)

**Comment by bk138** [comment] 2023-01-15 19:51
Dupe of #114, please subscribe there.

**Closed by bk138** 2023-01-15 19:51 UTC
Labels: bug
