### ISSUE TITLE
Failed Parsing Config

### ISSUE THREAD

**Issue by alkaris2** [bk138/gromit-mpx#211] opened 2024-08-29 05:16 UTC
**Describe the bug**
Config fails to read the syntax of the config file and doesn't work properly. Even though I copy the exact config syntaxing and all the rest of it, the default config file provided in `/etc/gromit-mpx` is the issue, it doesn't know what the config parse should be when reading the defaults.

Also displays error with:
> `Expected name of Tool to define or Hot key definition`

**To Reproduce**
1. Start Gromit-MPX without config
2. Grab skeleton config from `/etc/gromit-mpx`
3. Change nothing
4. Start Gromit-MPX, get shown error `Failed parsing config file /home/user/.config/gromit-mpx.cfg falling back to default tools.`

**Expected Behavior**
Read config and just work

**Screenshots**

**Environment (please complete the following information):**
 - Gromit-MPX version: 1.6.0
 - Flatpak or Distribution-package or Built-from-source: tried both AUR & Git Source
 - OS and version: Manjaro Linux
 - Desktop Environment and version: Cinnamon
 - X11 or Wayland session: Xwayland

In a custom config I've tried the following; and Gromit-MPX fails to parse anything.  The problem lies with the parsing, Gromit-MPX clearly needs to have it's syntax parsing checked and rebuilt if it can't read it's own syntax's for the config file because it's bugged if it's unable to read the default config file or a custom config file. I would just remake the syntax it reads for the file in a more easily readable format that it understands for typical config files. The documentation around it's details of the config file and syntaxes for this tool is really poorly underdocumented, and it's mostly guess work as to WHAT actually works and what doesn't, and the errors it produces aren't exactly helpful either, it can't even point out what lines are wrong and failing to parse at, and giving vague and impossible errors that don't mean anything or give any description of what the errors even means.

If you're given an error that states;
> Expected name of Tool to define or Hot key definition

What does that message even suppose to mean to someone who's trying to configure it? This is where I would be considering putting helpful information about it, a support link or mention of something to put you in the right directly, this is just the example of what I mean about poor documentation here. Link to the Wiki page that details this information.

Other obscure errors that doesn't have any context to what it means;

`WARNING: Unable to copy "red Pen|@0": not yet defined!`

as an example of a misconfiguration, you might be given a warning message, but doesn't mention what it means by *"not yet defined"* this is where I would put extra notes showing how to define something in the config file.

For the **Super-Obscure** Error messages;
`Expected ";"`

Doesn't mention where it expects this `;` character in the config, you need to specify what line it's failing and where it's expecting a certain character at on what line, instead of absolutely nothing to go on. **LINE** what on **COLUMN** what? 

Proper Error messages for syntax errors would be like this;

```
Syntax error on line 13, column 17
Expected ";"
```

```
# GROMIT-MPX
workspace = special:gromit, gapsin:0, gapsout:0, on-created-empty: gromit-mpx -a
windowrule = noblur, ^(Gromit-mpx)$
windowrule = opacity 1 override, 1 override, ^(Gromit-mpx)$
windowrule = noshadow, ^(Gromit-mpx)$
windowrule = nofullscreenrequest, ^(Gromit-mpx)$
windowrule = size 100% 100%, ^(Gromit-mpx)$
bind = , F7, togglespecialworkspace, gromit
bind = SHIFT , F7, exec, gromit-mpx --clear
bind = , F6, exec, gromit-mpx --undo
bind = SHIFT , F6, exec, gromit-mpx --redo

# pen colors and style
"red Pen" = PEN        (size=3 color="#dc5644");
"blue Pen" = "red Pen"; (size=3 color="#6e89d5");
"yellow Pen" = "red Pen"; (size=3 color="#dfb063");
"green Pen" = "red Pen"; (size=3 color="#aed854");
"white Pen" = "red Pen"; (size=3 color="#ffffff");

# Line Tool
"green Line" = LINE; (minsize=3 color="#aed854");

# Rect Tool
"yellow Rectangle" = LINE; (minsize=3 color="#dfb063");

# Eraser
"Eraser" = ERASER (size=5);

# define device input
"Core Pointer"    = "red Pen";
"Core Pointer"[1] = "red Pen";
"Core Pointer"[2] = "blue Pen";
"Core Pointer"[3] = "green Pen";
"Core Pointer"[4] = "yellow Pen";
"Core Pointer"[5] = "white Pen";
"Core Pointer"[6] = "Eraser";
```

**Comment by bk138** [comment] 2024-08-29 09:57
Thanks for your report. Please paste the config in question.

**Comment by bk138** [comment] 2024-09-04 05:21
Tentatively closing. Please post new info here once available.

**Comment by grantcarthew** [comment] 2024-09-04 05:39
Dude. These guys don't get paid for the hard work they do. They do not need someone to be rude to them in an open-source issue tracking system.

Please apologise and if you are in a hurry to get it fixed, offer them some cash.

No, I'm not affiliated with the developers in this project. I just saw your comment and am so surprised that people with such a bad attitude exist in this world. Please correct this.

**Comment by grantcarthew** [comment] 2024-09-04 05:43
![image](https://github.com/user-attachments/assets/d269bd05-00cc-4120-a59b-f5ac17f76cf8)

**Comment by bk138** [comment] 2024-09-04 07:47
@alkaris2 Please watch you language and consider rethinking your attitude towards others. I refrain from interacting with people that yell at me. The config snippet you listed above is _not_ Gromit-MPX's default config. The default config is https://github.com/bk138/gromit-mpx/blob/master/data/gromit-mpx.cfg

**Comment by dharabor** [comment] 2024-09-06 08:58
Hi, 

Thank you for the great tool. I do not agree at all with the tone from @alkaris2, but I do think there might be an actual bug here. I've been trying to unsuccessfully to change to the default pen type to anything else but without success, no matter what I put in the config file. No error is reported when starting the app (1.6.0, system-wide flatpak)  either, at least when doing so from the Pop_OS (22.04) launcher. However when launching the app from the command line two errors appear: 

1. An error dialog with the text 
> "Failed parsing config file in /home/user/.config/gromit-mpx.cfg, falling back to default tools

2. An error is output to the console: 
> Expected Tool-definition or name of template tool

These errors appear no matter what is in the configuration file. For example, I tried the one indicated by @bk138 above.

Two further observations: 

(a). It is possible to change the configuration if one directly edits the file at
> /var/lib/flatpak/app/net.christianbeier.Gromit-MPX/x86_64/stable/active/files/etc/gromit-mpx/gromit-mpx.cfg 

this file seems to be an [older](https://github.com/bk138/gromit-mpx/blob/f7a76980249ebd3fab98eabc48d5be0c6893f40b/data/gromit-mpx.cfg) default configuration. 

(b) attempting to add configuration options like SMOOTH and ORTHO to this file results in error (1) appearing, no matter how the app is launched. Other options, such as PEN and LINE and their colour attributes work fine. 

A similar issue affects the version from the Pop_OS apt repository (1.4.2), although I did not spend as much time trying to track down the problem.

**Comment by bk138** [comment] 2024-09-06 10:30
@dharabor thanks for the observations, I'll have a look!

**Comment by MattPereira** [comment] 2024-09-07 01:27
gm I'm a new user who's also struggling to edit config. I'm on `Ubuntu 22.04.4`

Read the docs several times and tried installing / uninstalling with both flatpak and apt, but get the same error as @dharabor anytime i try to add a custom config file

Is there a default hotkey for green or is only red / blue / yellow available?

**Comment by bk138** [comment] 2024-09-09 19:30
v1.7.0 is being rolled out on flathub, let me know if this fixes the issue for you.

**Comment by dharabor** [comment] 2024-09-10 10:23
Hi, 

Thank you very much @bk138 for such prompt attention to this issue. I updated to 1.7.0 and I can confirm that things are much improved. The configuration is now read correctly, which is great, and I appreciated the "Edit Config" feature for quickly locating and opening the relevant file!

One slightly unexpected behaviour (might be flatpak?) is that the app loads the system configuration if the user configuration is a symlink instead of a regular file (at some point in earlier testing I sym-linked the flatpak user config to a the traditional location $HOME/.config/gromit-mpx.cfg). When I remove the sym-link and use a regular file, the flatpak user config is loaded correctly. 

I also tried the new controls for changing line opacity and thickness. These did not seem to do anything.

**Comment by bk138** [comment] 2024-09-10 10:47
@dharabor `"green Line" = LINE (color="green" size=15);` gives me a rather bold line. AFAIR there's no per-tool opacity config. Opacity is for the whole screen.

**Comment by dharabor** [comment] 2024-09-11 06:18
@bk138 Thanks for clarifying the functionality of the opacity feature! I thought it was applicable to subsequent lines.  What about the "Thicker lines" and "Thinner lines" drop-down options? I could not detect any difference after selecting these options, either to subsequent lines or previously drawn lines. I tried selecting them several times, thinking the effect might stack, but again, no difference.  

Adjusting thickness from the configuration file meanwhile, as you suggested, works great.

**Comment by bk138** [comment] 2024-09-11 10:12
@dharabor Let's track the line thickener issue in  #212, I'll close this one as it should be resolved now.

**Closed by bk138** 2024-09-11 10:12 UTC
Labels: bug, answer-needed
