### ISSUE TITLE
xubuntu 20.04 no funciona

### ISSUE THREAD

**Issue by marcelofajardo** [bk138/gromit-mpx#84] opened 2020-05-06 00:08 UTC
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/gromit-mpx

**Describe the bug**
no funciona en xubuntu 20.04 focal fossa

**To Reproduce**
Tool name: "yellow Pen|@0       ": Pen,     width:   5, minwidth:   1, arrowsize: 0,00, color: rgb(255,255,0)
Tool name: "default|@2          ": Pen,     width:   5, minwidth:   1, arrowsize: 0,00, color: rgb(255,255,0)
Tool name: "blue Pen|@0         ": Pen,     width:   5, minwidth:   1, arrowsize: 0,00, color: rgb(0,0,255)
Tool name: "red Pen|@0          ": Pen,     width:   5, minwidth:   1, arrowsize: 0,00, color: rgb(255,0,0)
Tool name: "Eraser|@0           ": Eraser,  width:  75, minwidth:   1, arrowsize: 0,00, color: rgb(255,0,0)
Tool name: "default|@0          ": Pen,     width:   5, minwidth:   1, arrowsize: 0,00, color: rgb(255,0,0)
Tool name: "default|@1          ": Pen,     width:   5, minwidth:   1, arrowsize: 0,00, color: rgb(0,0,255)
Tool name: "default|D0          ": Eraser,  width:  75, minwidth:   1, arrowsize: 0,00, color: rgb(255,0,0)
Tool name: "green Marker|@0     ": Pen,     width:   6, minwidth:   1, arrowsize: 1,00, color: rgb(0,128,0)
Tool name: "default|B0          ": Pen,     width:   6, minwidth:   1, arrowsize: 1,00, color: rgb(0,128,0)
Supported backends: x11 wayland 
Using backend: x11
DEBUG: Ungrabbed all Devices.
DEBUG: Grabbing hotkeys from keyboard '3' .
Enabled Device 0: "Virtual core pointer", (Type: 0)
Now 1 enabled devices.
DEBUG: Ungrabbed all Devices.
DEBUG: Hiding window.
DEBUG: got configure event

**Desktop (please complete the following information):**
 - xubuntu 20.04 focal fossa kernel 5.4.0-28-generic
 - Xorg version used: X.Org X Server 1.20.8

**Comment by bk138** [comment] 2020-05-06 07:45
dupe of #77, it seems. If not, please re-open :-).

**Closed by bk138** 2020-05-06 07:45 UTC
Labels: bug
